### ISSUE TITLE
No such file or directory: '../data/pororo/descriptions_vec_512.pkl'

### ISSUE THREAD

**Issue by cgnerds** [adymaharana/storydalle#1]
Thank you for sharing your work. I'd like to train the model, but when I ran the command "bash train_story.sh pororo ", it shows that error as follows. Can you kindly check data.zip file of the pororo datasets? Thank you very much!
![image](https://user-images.githubusercontent.com/3292333/190849938-414e17bb-bd2e-44a1-a618-49adc2050833.png)

**Comment by adymaharana** [comment]
Hi, thanks for taking interest in this work! The download link has been updated to include this file. Let me know in this thread if you run into any other issues with the data.
