### ISSUE TITLE
The flintstone dataset

### ISSUE THREAD

**Issue by wenyuqing** [adymaharana/storydalle#14]
Hi, thanks for your awesome work! I noticed that you proposed the flintstoneSV dataset based on the original flintstone dataset, where the video frames are sampled. I'm wondering could you please provide me with the original complete flintstone dataset for better video generation? I cannot find it anywhere.
I'm looking forward to your reply, thanks!

**Comment by adymaharana** [comment]
Hi, thanks for finding our work useful! Could you please try this link for downloading the original Flintstones dataset: https://www.kaggle.com/datasets/danielsalami/video-frames-4 ?

**Comment by YuqingWang1029** [comment]
Hi @adymaharana, thanks for your awesome work.  I also want to request for the original video dataset. I download the dataset in the link https://www.kaggle.com/datasets/danielsalami/video-frames-4  and find the file only contains a subset of the original dataset, without the original id and caption data. Could you please provide the original complete flintstone dataset for better video generation? Looking forward to your reply, thanks!

**Comment by adymaharana** [comment]
Hi @Epiphqny, thank you for your interest in our work! Unfortunately, I no longer have the original dataset in my archives. Could you please reach out to the authors of the paper that introduced the dataset: [Imagine This! Scripts to Compositions to Videos](https://prior.allenai.org/projects/craft)?
