### ISSUE TITLE
where can I install vfid?

### ISSUE THREAD

**Issue by xichenpan** [adymaharana/storydalle#2]
Thanks for your awesome work! I see that "from vfid.fid_score import fid_score" in your code, where can I install vfid lib? or where can I find the code?

**Comment by adymaharana** [comment]
Hello,

Thank you so much for your interest in our work! And apologies for the delay in attending to this issue. I have updated the codebase with the vfid scripts. The vfid scripts are based on the scripts [here](https://github.com/basiclab/CPCStoryVisualization-Pytorch/tree/master/fid) with modifications.

**Comment by xichenpan** [comment]
Thanks a lot for your response!

**Comment by xichenpan** [comment]
Thanks a lot for the response!

Best,
Xichen

Adyasha Maharana ***@***.***> 于 2022年10月4日周二 13:03写道：
