### ISSUE TITLE
Difficulties about reproduce results on FlintStones

### ISSUE THREAD

**Issue by xichenpan** [adymaharana/storydalle#7]
Hi, I am currently working on reproduce StoryDALLE on Flintstones
I use the provided code and trained mega model for 50 epochs in a lr of 1e-5.
the FID is 32 and my generation results are poor compared to the figure 4 in your paper. blow are my generated images, the right ones are grount truth.
![2_s0415_f0](https://user-images.githubusercontent.com/48356412/197517151-b33de49b-1306-4ae5-96f6-1625118d1a3f.png)
![2_s0415_f1](https://user-images.githubusercontent.com/48356412/197517147-4bc63f8c-9f16-4d5c-a97b-04561bac8dd0.png)
![2_s0415_f2](https://user-images.githubusercontent.com/48356412/197517146-e2c0719a-5e81-405b-aba5-b7f16356cc10.png)
![2_s0415_f3](https://user-images.githubusercontent.com/48356412/197517143-c0020933-ce7a-41f4-a020-9ba484c12ed3.png)
I think the reason maybe I am using the inference code in your training codebase. Am I using the correct method to generate images?
```python
pixels = model.sample_images(texts, src_images).cpu().transpose(1, -1).transpose(-1, -2)
```
I wil appreciate it if you can give me any advise~

**Comment by FeiiYin** [comment]
@Flash-321 
Hi, Flash, I faced problems during the inference stage.
`from dalle.models import PrefixTuningDalle, StoryDalle, PromptDalle` the code in `infer_t2i.py`
However, I did not find any files in the folder of `Dalle`. 
Can you share the files with me or did I miss anything?

Thanks in advance.

**Comment by xichenpan** [comment]
> 

Hi there, sorry I am not the repo owner and I do not know the detail. For my reproduction, I use mega-storydalle and finetune all params. It worked fine.
